version: '{build}'
install:
- cmd: >-
    choco install -y --allow-empty-checksums strawberryperl -version 5.20.1.1

    SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%

    cpanm --notest --quiet --installdeps .
build: off
test_script:
- cmd: prove -l -r t/
