version: '{build}'
install:
- cmd: >-
    choco install -y --allow-empty-checksums strawberryperl -version 5.28.0.1

    SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%

    cpanm --notest --quiet --installdeps .
build: off
cache:
  - C:\strawberry -> .appveyor.yml
  - C:\ProgramData\chocolatey\bin -> .appveyor.yml
  - C:\ProgramData\chocolatey\lib -> .appveyor.yml
  - C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\ -> .appveyor.yml
test_script:
- cmd: prove -l -r t/
