sudo: false
language: perl
perl:
    - "5.24"
    - "5.26"
    - "5.28"
before_install:
    - cpanm -n https://github.com/kritikaio/devel-cover-report-kritika-perl/archive/master.tar.gz
install:
    - cpanm -n -q --with-recommends --skip-satisfied --installdeps .
script:
    - perl Build.PL && ./Build build && ./Build test
    - cover -test -report kritika
